version: '3.8'

services:
  backend:
    build:
      context: ./Backend
      dockerfile: ./Dockerfile
    #restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./Backend:/code

  frontend:
    image: frontend:production
    ports:
      - "8080:3000"
    build:
      context: ./Frontend
      dockerfile: ./Dockerfile
