version: '1.2'

services:
  db:
    image: postgres:latest
    #restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  backend:
    build:
      dockerfile: ./Backend/Dockerfile
    container_name: backend
    command: python manage.py runserver 127.0.0.1:8081 --settings=settings.development
    #restart: always
    ports:
      - "8081:8081"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db

  frontend:
    container_name: gdpm-frontend
    ports:
      - 8080:3000
    build:
      dockerfile: ./Frontend/Dockerfile
      tags:
        - "production"
